name: Post Management

on:
  repository_dispatch:
    types: [create-post, update-post, delete-post]

jobs:
  manage-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Post
        if: github.event.action == 'create-post'
        run: |
          echo "${{ github.event.client_payload.content }}" > "contents/${{ github.event.client_payload.filename }}"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "contents/${{ github.event.client_payload.filename }}"
          git commit -m "Create post: ${{ github.event.client_payload.filename }}"
          git push

      - name: Update Post
        if: github.event.action == 'update-post'
        run: |
          if [ -f "contents/${{ github.event.client_payload.filename }}" ]; then
            echo "${{ github.event.client_payload.content }}" > "contents/${{ github.event.client_payload.filename }}"
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add "contents/${{ github.event.client_payload.filename }}"
            git commit -m "Update post: ${{ github.event.client_payload.filename }}"
            git push
          else
            echo "File not found: ${{ github.event.client_payload.filename }}"
            exit 1
          fi

      - name: Delete Post
        if: github.event.action == 'delete-post'
        run: |
          if [ -f "contents/${{ github.event.client_payload.filename }}" ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git rm "contents/${{ github.event.client_payload.filename }}"
            git commit -m "Delete post: ${{ github.event.client_payload.filename }}"
            git push
          else
            echo "File not found: ${{ github.event.client_payload.filename }}"
            exit 1
          fi
